// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type GenderType string

const (
	GenderTypeMale   GenderType = "male"
	GenderTypeFemale GenderType = "female"
	GenderTypeOther  GenderType = "other"
)

func (e *GenderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GenderType(s)
	case string:
		*e = GenderType(s)
	default:
		return fmt.Errorf("unsupported scan type for GenderType: %T", src)
	}
	return nil
}

type NullGenderType struct {
	GenderType GenderType `json:"gender_type"`
	Valid      bool       `json:"valid"` // Valid is true if GenderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGenderType) Scan(value interface{}) error {
	if value == nil {
		ns.GenderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GenderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGenderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GenderType), nil
}

type Example struct {
	ID          int32       `json:"id"`
	Description pgtype.Text `json:"description"`
}

type User struct {
	ID        pgtype.UUID      `json:"id"`
	Username  string           `json:"username"`
	Password  string           `json:"password"`
	FirstName pgtype.Text      `json:"first_name"`
	LastName  pgtype.Text      `json:"last_name"`
	Gender    NullGenderType   `json:"gender"`
	Email     pgtype.Text      `json:"email"`
	Phone     pgtype.Text      `json:"phone"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
